---
# <- yaml supports comments, json does not
# did you know you can embed json in yaml?
# try uncommenting the next line
# { foo: 'bar' }

config:
  - rigidyaml
  - better for data interchange
name:
  - slim and flexible
  - better for configuration
